config:
  # - coco_path: "coco_annotations.json"
  #   output_path: "standard"
  #   prompt_type: "bbox"
  #   clip_length: null
  #   variable_cats: false
  #   save_video_list: null
  #   noised_prompt: false
  #   rand_points_num: 0
  
  - coco_path: "coco_annotations.json"
    output_path: "noised"
    prompt_type: "bbox"
    clip_length: null
    variable_cats: false
    save_video_list: null
    noised_prompt: true
    rand_points_num: 0

  - coco_path: "coco_annotations.json"
    output_path: "standard"
    prompt_type: "mask"
    clip_length: null
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 0

  - coco_path: "coco_annotations.json"
    output_path: "noised"
    prompt_type: "mask"
    clip_length: null
    variable_cats: false
    save_video_list: null
    noised_prompt: true
    rand_points_num: 0
  
  - coco_path: "coco_annotations.json"
    output_path: "center"
    prompt_type: "points"
    clip_length: null
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 0

  - coco_path: "coco_annotations.json"
    output_path: "random_1"
    prompt_type: "points"
    clip_length: null
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 1

  - coco_path: "coco_annotations.json"
    output_path: "random_3"
    prompt_type: "points"
    clip_length: null
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 3

  - coco_path: "coco_annotations.json"
    output_path: "random_5"
    prompt_type: "points"
    clip_length: null
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 5
  
  - coco_path: "coco_annotations.json"
    output_path: "center_30_frames"
    prompt_type: "points"
    clip_length: 30
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 0

  - coco_path: "coco_annotations.json"
    output_path: "random_1_30_frames"
    prompt_type: "points"
    clip_length: 30
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 1

  - coco_path: "coco_annotations.json"
    output_path: "random_3_30_frames"
    prompt_type: "points"
    clip_length: 30
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 3
    
  - coco_path: "coco_annotations.json"
    output_path: "random_1_60_frames"
    prompt_type: "points"
    clip_length: 60
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 1

  - coco_path: "coco_annotations.json"
    output_path: "random_3_60_frames"
    prompt_type: "points"
    clip_length: 60
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 3

  - coco_path: "coco_annotations.json"
    output_path: "bbox_30_frames"
    prompt_type: "bbox"
    clip_length: 30
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 0

  - coco_path: "coco_annotations.json"
    output_path: "bbox_60_frames"
    prompt_type: "bbox"
    clip_length: 60
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 0

  - coco_path: "coco_annotations.json"
    output_path: "mask_30_frames"
    prompt_type: "mask"
    clip_length: 30
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 0

  - coco_path: "coco_annotations.json"
    output_path: "mask_60_frames"
    prompt_type: "mask"
    clip_length: 60
    variable_cats: false
    save_video_list: null
    noised_prompt: false
    rand_points_num: 0